"""Tests for the OpenAPI export.

This script is what CI's drift check runs, so a bug here silently disables that
guard rather than failing loudly.
"""

import json
from pathlib import Path

import pytest

from app import openapi_export


def test_schema_has_expected_shape() -> None:
    schema = openapi_export.build_schema()

    version = schema["openapi"]
    assert isinstance(version, str)
    assert version.startswith("3.")

    paths = schema["paths"]
    assert isinstance(paths, dict)
    assert "/healthz" in paths
    assert "/readyz" in paths


def test_output_is_deterministic(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """Two runs must produce byte-identical files.

    The drift check compares committed bytes against regenerated bytes. If key
    ordering or formatting varied between runs, CI would fail on every PR
    regardless of whether the API changed, and the check would be turned off.
    """
    target = tmp_path / "openapi.json"
    monkeypatch.setattr(openapi_export, "OUTPUT_PATH", target)

    openapi_export.main()
    first = target.read_text()
    openapi_export.main()
    second = target.read_text()

    assert first == second
    assert first.endswith("\n"), "missing trailing newline upsets diffs"
    json.loads(first)


def test_committed_schema_is_current() -> None:
    """The same invariant CI enforces, checked locally.

    Without this you discover a stale schema after pushing; with it, `pytest`
    tells you before the commit.
    """
    committed = openapi_export.OUTPUT_PATH.read_text()
    regenerated = json.dumps(openapi_export.build_schema(), indent=2, sort_keys=True) + "\n"
    assert committed == regenerated, (
        "openapi.json is stale — run `uv run export-openapi` and commit the result"
    )
