"""identity, roles and RLS

Creates the three database roles from ADR-0003, the identity tables, and the
Row-Level Security policies that make tenant isolation a property of the
database rather than a convention in application code.

Revision ID: 9f1332ec467f
Revises:
Create Date: 2026-08-22
"""

import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9f1332ec467f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APP_ROLE = "ai_app"
WORKER_ROLE = "ai_worker"

# Tables reachable by the application, each getting the identical pair of
# per-role policies. Listing them here rather than repeating the SQL keeps a
# new table from accidentally shipping with only one role's policy.
# Table -> the column identifying its owner. `app_user` is its own tenant, so
# the owner is the primary key itself; a separate owner_id column would be
# redundant and unfillable (the id is generated by the database default, so no
# INSERT could supply a matching value).
OWNED_TABLES: dict[str, str] = {
    "app_user": "id",
    "session_token": "owner_id",
}

# Postgres does not accept bind parameters for identifiers, so role and table
# names must be interpolated into DDL. That is only safe while the values are
# known-good identifiers, so assert it rather than assume it — the check runs at
# import, long before any statement is sent.
_SAFE_IDENTIFIER = re.compile(r"^[a-z_][a-z0-9_]{0,62}$")
for _identifier in (APP_ROLE, WORKER_ROLE, *OWNED_TABLES, *OWNED_TABLES.values()):
    if not _SAFE_IDENTIFIER.match(_identifier):
        raise ValueError(f"unsafe SQL identifier in migration: {_identifier!r}")


def _create_roles() -> None:
    """Roles are cluster-wide, so this must tolerate them already existing.

    They are created NOLOGIN and without a password: credentials are granted
    separately by `bootstrap-db-roles`, so no secret is ever written into a
    migration file that gets committed.

    On a managed provider that forbids CREATE ROLE, provision the two roles out
    of band first; the guard below then makes this a no-op.
    """
    for role in (APP_ROLE, WORKER_ROLE):
        op.execute(
            sa.text(f"""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
                    CREATE ROLE {role} NOLOGIN;
                END IF;
            END
            $$;
            """)
        )
        op.execute(sa.text(f"GRANT USAGE ON SCHEMA public TO {role}"))


def _create_owner_helper() -> None:
    """Resolve the current tenant, failing closed when unset.

    `current_setting(..., true)` returns NULL rather than raising when the
    setting is missing. Every policy compares `owner_id = app_current_owner()`,
    and comparing to NULL yields NULL — not true — so an unscoped query returns
    no rows instead of every row. The mistake shows up as an empty result in
    development, never as a cross-tenant leak in production.
    """
    op.execute(
        sa.text("""
        CREATE FUNCTION app_current_owner() RETURNS uuid
        LANGUAGE sql
        STABLE
        SET search_path = pg_catalog, public, pg_temp
        AS $$
            SELECT nullif(current_setting('app.owner_id', true), '')::uuid
        $$;
        """)
    )


def _create_updated_at_trigger() -> None:
    """Stamp updated_at in the database, not the ORM.

    A row changed by a migration or a manual psql session gets the same
    treatment as one changed through the application.
    """
    op.execute(
        sa.text("""
        CREATE FUNCTION set_updated_at() RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog, public, pg_temp
        AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END
        $$;
        """)
    )


def _enable_rls(table: str, owner_column: str) -> None:
    """Apply the ADR-0003 policy pair to one table.

    FORCE matters: a table owner is otherwise exempt from its own policies, so
    an application that accidentally connected as the owning role would bypass
    RLS entirely and see every tenant — a silent, total failure. With FORCE and
    no owner policy, that same misconfiguration returns zero rows instead.
    """
    op.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
    op.execute(sa.text(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY"))

    # Application: own tenant, non-deleted rows only. The soft-delete predicate
    # lives here as well as in repository queries, so a forgotten filter in one
    # hand-written query returns too few rows rather than resurfacing deleted
    # PII.
    op.execute(
        sa.text(f"""
        CREATE POLICY {table}_app ON {table}
            FOR ALL TO {APP_ROLE}
            USING ({owner_column} = app_current_owner() AND deleted_at IS NULL)
            WITH CHECK ({owner_column} = app_current_owner());
        """)
    )

    # Worker: identical tenant scoping, but soft-deleted rows stay visible,
    # because purging them is precisely its job.
    op.execute(
        sa.text(f"""
        CREATE POLICY {table}_worker ON {table}
            FOR ALL TO {WORKER_ROLE}
            USING ({owner_column} = app_current_owner())
            WITH CHECK ({owner_column} = app_current_owner());
        """)
    )

    op.execute(
        sa.text(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {APP_ROLE}, {WORKER_ROLE}")
    )


def _create_auth_functions() -> None:
    """The two lookups that necessarily precede knowing the tenant.

    Authentication establishes `app.owner_id`; it cannot also depend on it.
    Rather than dropping RLS from the two most sensitive tables, each lookup is
    a SECURITY DEFINER function granted only to the application role.

    `SET search_path` is mandatory here, not stylistic. Without it a caller able
    to create objects in an earlier schema can shadow a table or operator the
    body references and have it run with the definer's privileges — the classic
    SECURITY DEFINER escalation.
    """
    op.execute(
        sa.text("""
        CREATE FUNCTION auth_lookup_user_by_email(p_email text)
        RETURNS TABLE (user_id uuid, password_hash text)
        LANGUAGE sql
        SECURITY DEFINER
        STABLE
        SET search_path = pg_catalog, public, pg_temp
        AS $$
            SELECT id, password_hash
            FROM app_user
            WHERE email = lower(p_email)
              AND deleted_at IS NULL
        $$;
        """)
    )
    op.execute(
        sa.text("""
        CREATE FUNCTION auth_resolve_session(p_token_hash bytea)
        RETURNS TABLE (session_id uuid, owner_id uuid)
        LANGUAGE sql
        SECURITY DEFINER
        STABLE
        SET search_path = pg_catalog, public, pg_temp
        AS $$
            SELECT s.id, s.owner_id
            FROM session_token s
            JOIN app_user u ON u.id = s.owner_id
            WHERE s.token_hash = p_token_hash
              AND s.revoked_at IS NULL
              AND s.expires_at > now()
              AND u.deleted_at IS NULL
        $$;
        """)
    )
    op.execute(
        sa.text("""
        CREATE FUNCTION auth_register_user(p_email text, p_password_hash text)
        RETURNS uuid
        LANGUAGE sql
        SECURITY DEFINER
        VOLATILE
        SET search_path = pg_catalog, public, pg_temp
        AS $$
            INSERT INTO app_user (email, password_hash)
            VALUES (lower(p_email), p_password_hash)
            RETURNING id
        $$;
        """)
    )

    # EXECUTE is revoked from PUBLIC first: functions are executable by everyone
    # by default, and a SECURITY DEFINER function open to PUBLIC is a hole.
    for fn in (
        "auth_lookup_user_by_email(text)",
        "auth_resolve_session(bytea)",
        "auth_register_user(text, text)",
    ):
        op.execute(sa.text(f"REVOKE ALL ON FUNCTION {fn} FROM PUBLIC"))
        op.execute(sa.text(f"GRANT EXECUTE ON FUNCTION {fn} TO {APP_ROLE}"))


def upgrade() -> None:
    _create_roles()
    _create_owner_helper()
    _create_updated_at_trigger()

    op.create_table(
        "app_user",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.dialects.postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.dialects.postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            sa.dialects.postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_app_user"),
        sa.UniqueConstraint("email", name="uq_app_user_email"),
    )

    op.create_table(
        "session_token",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.dialects.postgresql.BYTEA(), nullable=False),
        sa.Column(
            "created_at",
            sa.dialects.postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.dialects.postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "revoked_at",
            sa.dialects.postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_used_at",
            sa.dialects.postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "deleted_at",
            sa.dialects.postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["app_user.id"],
            name="fk_session_token_owner_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_session_token"),
        sa.UniqueConstraint("token_hash", name="uq_session_token_token_hash"),
    )
    op.create_index("ix_session_token_owner_id", "session_token", ["owner_id"])
    op.create_index("ix_session_token_expires_at", "session_token", ["expires_at"])

    op.execute(
        sa.text(
            "CREATE TRIGGER app_user_set_updated_at BEFORE UPDATE ON app_user "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )
    )

    for table, owner_column in OWNED_TABLES.items():
        _enable_rls(table, owner_column)

    _create_auth_functions()


def downgrade() -> None:
    for fn in (
        "auth_lookup_user_by_email(text)",
        "auth_resolve_session(bytea)",
        "auth_register_user(text, text)",
    ):
        op.execute(sa.text(f"DROP FUNCTION IF EXISTS {fn}"))

    op.drop_table("session_token")
    op.drop_table("app_user")

    op.execute(sa.text("DROP FUNCTION IF EXISTS set_updated_at()"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS app_current_owner()"))

    # Roles are intentionally NOT dropped. They are cluster-wide and may own
    # grants in other databases; dropping them on a downgrade is a wider blast
    # radius than the migration's own scope.
