"""Declarative base and shared column conventions."""

import uuid
from datetime import datetime

from sqlalchemy import MetaData, func
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit constraint naming. Postgres will happily invent names like
# `document_owner_id_fkey1`, and Alembic's autogenerate then cannot reliably
# emit a DROP for them, so migrations silently diverge from the models. Naming
# every constraint deterministically is what makes autogenerate trustworthy.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk() -> Mapped[uuid.UUID]:
    """Primary key generated by the database.

    `gen_random_uuid()` is core in Postgres 13+, so the value exists even for
    rows inserted outside the application — a migration, a manual fix, a bulk
    load. Generating it in Python would leave those paths without a default.
    """
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )


def created_at_column() -> Mapped[datetime]:
    return mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


def updated_at_column() -> Mapped[datetime]:
    # Maintained by a trigger rather than the ORM, so rows changed by a
    # migration or by psql are also stamped.
    return mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


def deleted_at_column() -> Mapped[datetime | None]:
    """Soft deletion marker.

    Rows carrying a non-NULL value are invisible to the application role: the
    predicate lives in the RLS policy as well as in repository queries, so
    forgetting it in one hand-written query returns too few rows rather than
    resurfacing deleted data (ADR-0003).
    """
    return mapped_column(TIMESTAMP(timezone=True), nullable=True, default=None)
